"""
Analytical Reports Export API.
Supports PDF/CSV triggers and downloads.
"""
import os
from flask import send_file
from flask.views import MethodView
from flask_smorest import Blueprint, abort
from flask_jwt_extended import jwt_required, get_jwt_identity, get_jwt
from marshmallow import Schema, fields
from app.models.report import Report
from app.services.report_service import ReportService
from app.extensions import db

reports_blp = Blueprint("reports", "reports", url_prefix="/api/reports", description="Report operations")

class ReportRequestSchema(Schema):
    report_type = fields.Str(required=True)
    title = fields.Str(required=True)
    format = fields.Str(required=True)
    parameters = fields.Dict(required=False)

@reports_blp.route("/")
class ListReportsView(MethodView):
    
    @jwt_required()
    def get(self):
        """Lists reports generated by internal users."""
        reports = Report.query.order_by(Report.created_at.desc()).all()
        return [r.to_dict() for r in reports], 200

@reports_blp.route("/generate")
class GenerateReportView(MethodView):
    
    @jwt_required()
    @reports_blp.arguments(ReportRequestSchema)
    def post(self, req_data):
        """Triggers report generation job (PDF or CSV file creation)."""
        claims = get_jwt()
        if claims.get("role") not in ["admin", "analyst"]:
            abort(403, message="Insufficient permissions to generate reports.")
            
        user_id = int(get_jwt_identity())
        
        # Validate format
        fmt = req_data["format"].lower()
        if fmt not in ["pdf", "csv"]:
            abort(400, message="Format must be either 'pdf' or 'csv'.")
            
        # Create pending database record
        report = Report(
            generated_by=user_id,
            report_type=req_data["report_type"],
            title=req_data["title"],
            format=fmt,
            parameters=req_data.get("parameters", {}),
            status="pending"
        )
        db.session.add(report)
        db.session.commit()
        
        # For simplicity and immediacy in non-celery execution context, 
        # we generate the report synchronously here. In Celery workers, it runs asynchronously.
        filename = f"report_{report.id}.{fmt}"
        file_path = os.path.abspath(os.path.join("./reports", filename))
        
        try:
            report.status = "generating"
            db.session.commit()
            
            if fmt == "pdf":
                ReportService.generate_pdf_report(report.id, report.title, file_path, report.parameters)
            else:
                ReportService.generate_csv_report(report.id, file_path, report.parameters)
                
            report.status = "completed"
            report.file_path = file_path
            report.file_size_bytes = os.path.getsize(file_path) if os.path.exists(file_path) else 0
            db.session.commit()
            
        except Exception as e:
            report.status = "failed"
            report.error_message = str(e)
            db.session.commit()
            abort(500, message=f"Failed to generate report: {str(e)}")
            
        return {
            "message": "Report generated successfully.",
            "report": report.to_dict()
        }, 201

@reports_blp.route("/<int:report_id>/download")
class DownloadReportView(MethodView):
    
    @jwt_required()
    def get(self, report_id):
        """Serves the generated PDF / CSV file asset for download."""
        report = Report.query.get_or_404(report_id)
        if report.status != "completed" or not report.file_path:
            abort(400, message="Report file is not ready or failed to generate.")
            
        if not os.path.exists(report.file_path):
            abort(404, message="Report file asset not found on storage disk.")
            
        return send_file(
            report.file_path,
            as_attachment=True,
            download_name=os.path.basename(report.file_path)
        )
